import Head from "next/head";
import { SiNextdotjs } from "react-icons/si";
import Navigation from "./components/navigation";

const about = () => {
  return (
    <>
      <Head>
        <title>About Pages</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navigation />
      <main>
        <div className="flex flex-col items-center justify-center w-screen h-screen px-8 py-10 xl:px-96 gap-10 bg-slate-50">
          <div className="flex flex-col items-center justify-center">
            <SiNextdotjs size="50" />
            <h1 className="text-6xl font-bold tracking-tight">Next.js</h1>
          </div>
          <hr className="bg-gray-100 w-full h-0.5" />
          <div className="flex flex-col items-center justify-center gap-4 w-96">
            <h6 className="text-base font-semibold">What is Next.js ?</h6>
            <p className="text-sm font-base text-center tracking-normal  leading-6">
              Next.js is a flexible React framework that gives you building blocks to create fast web applications.
            </p>
          </div>
        </div>
      </main>
    </>
  );
};

export default about;
