import Head from "next/head";
import Navigation from "./components/navigation";

const about = () => {
  return (
    <>
      <Head>
        <title>About Pages</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <Navigation />
        <h1>About</h1>
      </div>
    </>
  );
};

export default about;
