import Head from "next/head";
import { useState } from "react";
// importing google font form @next/font
// rename DM_Serif_Display as DMSDisplay
// import { DM_Serif_Display as DMSDisplay } from "@next/font/google";
import Navigation from "./components/navigation";

// delcaring dmsd as DMSDisplay to create {dmsd.classname}
// const dmsd = DMSDisplay({ weight: "400", subsets: ["latin"] });

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);

  const toggle = () => {
    setIsOpen(!isOpen);
  };
  return (
    <>
      <Head>
        <title>Learn Next.js 13</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="flex flex-col h-screen">
        <header>
          <Navigation toggle={toggle} />
          {/* calling the dmsd function into className = {dmsd.className}
        <a href="/about">About</a>
        <Link href="/about">About Next Link</Link> */}
        </header>
        <main className="overflow-y-auto">
          <div className="flex flex-col items-center justify-center w-screen h-screen px-8 py-10 xl:px-96 gap-10 bg-slate-50">
            <div className="flex flex-col items-center justify-center">
              <h1 className="text-6xl font-bold tracking-tight">Next.js</h1>
            </div>
            <hr className="bg-gray-100 w-full h-0.5" />
            <div className="flex flex-col items-center justify-center gap-4 w-96">
              <h6 className="text-base font-semibold">What is Next.js ?</h6>
              <p className="text-sm font-base text-center tracking-normal  leading-6">
                Next.js is a flexible React framework that gives you building blocks to create fast web applications.
              </p>
            </div>
          </div>
          <div className="flex flex-col items-center justify-center w-screen h-screen px-8 py-10 xl:px-96 gap-10 bg-slate-50">
            <div className="flex flex-col items-center justify-center">
              <h1 className="text-6xl font-bold tracking-tight">Next.js</h1>
            </div>
            <hr className="bg-gray-100 w-full h-0.5" />
            <div className="flex flex-col items-center justify-center gap-4 w-96">
              <h6 className="text-base font-semibold">What is Next.js ?</h6>
              <p className="text-sm font-base text-center tracking-normal  leading-6">
                Next.js is a flexible React framework that gives you building blocks to create fast web applications.
              </p>
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
