import Head from "next/head";
import { DM_Serif_Display as DMSDisplay } from "@next/font/google";

const dmsd = DMSDisplay({ weight: "400", subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <h1 className={dmsd.className}> Hello</h1>
      </div>
    </>
  );
}
